/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Birds {
  id: string;
  name: string;
}

export interface Cards {
  card_cvv: number;
  card_expiration: string;
  card_issuer: string;
  card_num: number;
  id: string;
  user_id: string;
}

export interface Transactions {
  card_id: string;
  id: string;
  transaction_data: string;
}

export interface Users {
  id: string;
  user_name: string;
}

export interface DB {
  birds: Birds;
  cards: Cards;
  transactions: Transactions;
  users: Users;
}
